const experiences = [
    {
        title: "Teamwork",
        desc: "Donec sed odio tempor, varius elit eu, consequat urna. Morbi bibendum vestibulum maximus."
    },
    {
        title: "Self Development",
        desc: "Vestibulum ut nibh ex. Quisque nulla ante, tristique in efficitur eu, ultrices a justo."
    },
    {
        title: "Sociality",
        desc: "Praesentium error nostrum fuga tempore vitae veniam. Possimus quisquam similique."
    }
];

const testimonials = [
    {
        id: 1,
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore blanditiis corrupti eaque ipsa eveniet, reiciendis praesentium quia nostrum, iusto minima expedita, at eos. Laborum quod, quis ullam porro quia nihil.",
        name: "Flora Shepherd",
        role: "Designer"
    },
    {
        id: 2,
        text: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Labore corrupti laboriosam maxime, repudiandae debitis qui. Dolore saepe alias unde. Quis nemo nihil nam quam harum.",
        name: "Marcia Hensley",
        role: "Designer"
    },
    {
        id: 3,
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Necessitatibus deserunt et animi minus placeat numquam porro ex, doloribus deleniti error.",
        name: "Martin Flowers",
        role: "Business owner"
    },
    {
        id: 4,
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo porro eos placeat optio iusto dolorem nobis numquam, ex doloribus repellendus eaque et.",
        name: "Daniel Cooper",
        role: "Architect"
    },
    {
        id: 5,
        text: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Nihil repellendus reprehenderit a repellat corrupti pariatur sed? Nihil sapiente iste minus temporibus praesentium ",
        name: "Sophia Bennett",
        role: "Interior Designer"
    },
    {
        id: 6,
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. In quis porro vitae consequuntur perferendis eaque culpa. Quas quidem velit natus!",
        name: "James Walker",
        role: "Project Manager"
    },
    {
        id: 7,
        text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Eligendi veniam laboriosam consequatur ullam, quasi deleniti eveniet debitis dicta praesentium possimus voluptatum ut voluptas. Eveniet dicta repudiandae, amet illum quaerat fugit nesciunt aut architecto.",
        name: "Olivia Carter",
        role: "Home Owner"
    }
];

const countries = [
    "Afghanistan",
    "Afrique du Sud",
    "Albanie",
    "Algérie",
    "Allemagne",
    "Andorre",
    "Angola",
    "Antigua-et-Barbuda",
    "Arabie saoudite",
    "Argentine",
    "Arménie",
    "Australie",
    "Autriche",
    "Azerbaïdjan",
    "Bahamas",
    "Bahreïn",
    "Bangladesh",
    "Barbade",
    "Belgique",
    "Belize",
    "Bénin",
    "Bhoutan",
    "Biélorussie",
    "Birmanie",
    "Bolivie",
    "Bosnie-Herzégovine",
    "Botswana",
    "Brésil",
    "Brunei",
    "Bulgarie",
    "Burkina Faso",
    "Burundi",
    "Cambodge",
    "Cameroun",
    "Canada",
    "Cap-Vert",
    "Centrafrique",
    "Chili",
    "Chine",
    "Chypre",
    "Colombie",
    "Comores",
    "Congo-Brazzaville",
    "Congo-Kinshasa",
    "Corée du Nord",
    "Corée du Sud",
    "Costa Rica",
    "Côte d'Ivoire",
    "Croatie",
    "Cuba",
    "Danemark",
    "Djibouti",
    "Dominique",
    "Égypte",
    "Émirats arabes unis",
    "Équateur",
    "Érythrée",
    "Espagne",
    "Eswatini",
    "Estonie",
    "États-Unis",
    "Éthiopie",
    "Fidji",
    "Finlande",
    "France",
    "Gabon",
    "Gambie",
    "Géorgie",
    "Ghana",
    "Grèce",
    "Grenade",
    "Guatemala",
    "Guinée",
    "Guinée équatoriale",
    "Guinée-Bissau",
    "Guyana",
    "Haïti",
    "Honduras",
    "Hongrie",
    "Inde",
    "Indonésie",
    "Irak",
    "Iran",
    "Irlande",
    "Islande",
    "Israël",
    "Italie",
    "Jamaïque",
    "Japon",
    "Jordanie",
    "Kazakhstan",
    "Kenya",
    "Kirghizistan",
    "Kiribati",
    "Koweït",
    "Laos",
    "Lesotho",
    "Lettonie",
    "Liban",
    "Libéria",
    "Libye",
    "Liechtenstein",
    "Lituanie",
    "Luxembourg",
    "Macédoine du Nord",
    "Madagascar",
    "Malaisie",
    "Malawi",
    "Maldives",
    "Mali",
    "Malte",
    "Maroc",
    "Maurice",
    "Mauritanie",
    "Mexique",
    "Micronésie",
    "Moldavie",
    "Monaco",
    "Mongolie",
    "Monténégro",
    "Mozambique",
    "Namibie",
    "Nauru",
    "Népal",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "Norvège",
    "Nouvelle-Zélande",
    "Oman",
    "Ouganda",
    "Ouzbékistan",
    "Pakistan",
    "Palaos",
    "Palestine",
    "Panama",
    "Papouasie-Nouvelle-Guinée",
    "Paraguay",
    "Pays-Bas",
    "Pérou",
    "Philippines",
    "Pologne",
    "Portugal",
    "Qatar",
    "République dominicaine",
    "République tchèque",
    "Roumanie",
    "Royaume-Uni",
    "Russie",
    "Rwanda",
    "Saint-Christophe-et-Niévès",
    "Saint-Marin",
    "Saint-Vincent-et-les-Grenadines",
    "Sainte-Lucie",
    "Salomon",
    "Samoa",
    "Sao Tomé-et-Principe",
    "Sénégal",
    "Serbie",
    "Seychelles",
    "Sierra Leone",
    "Singapour",
    "Slovaquie",
    "Slovénie",
    "Somalie",
    "Soudan",
    "Soudan du Sud",
    "Sri Lanka",
    "Suède",
    "Suisse",
    "Suriname",
    "Syrie",
    "Tadjikistan",
    "Taïwan",
    "Tanzanie",
    "Tchad",
    "Thaïlande",
    "Timor oriental",
    "Togo",
    "Tonga",
    "Trinité-et-Tobago",
    "Tunisie",
    "Turkménistan",
    "Turquie",
    "Tuvalu",
    "Ukraine",
    "Uruguay",
    "Vanuatu",
    "Vatican",
    "Venezuela",
    "Viêt Nam",
    "Yémen",
    "Zambie",
    "Zimbabwe"
];

export default { experiences, testimonials, countries };